---
title: "clear and to the point - chapter1"
author: "Meiying Wang, Wang Chao"
date: "2020/6/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 1 Communication: clearly & effectively 8 principles

### Goal 1: Connect with your audience

#### P1: principle of relevance (what to communicate)
	* identify the takeaway message(s)
	* build everything relevant to the takeaway messages
	* give information that is only necessary and sufficient

		* too little → puzzled
		* too much → overwhelmed and disoriented

E.g. general difference between US & Japan: don't break information by gender/ region

#### P2: principle of appropriate knowledge (how to communicate)
	* know your audience 
	* make contact with what the audience already knows

a. language: jargon, sophistication & complexity of vocabulary & syntactic structureb. displays: bar graph vs. box-and-whisker chartc. concepts & information
	* address their concerns and interests

the more we reflect on material, the more likely it is that the material will stickE.g. link abstract ideas → everyday facts

### Goal 2: Direct and hold attention
	* possible distractors on a slide
	* lead the audience through the material step by step

#### P3: principle of salience
	* make key information salient (e.g. bold, font size, our brain tracks perceptible differences)
	* make irrelevancies not salient (e.g. infelicitous background patterns)
	* prioritize different aspects of the message (e.g. animation to call attention; gray out unimportant information)

#### P4: principle of discriminability
	* two properties must differ by a large enough proportion or they will not be distinguished
	* our visual systems register relative proportions, not absolute amounts

e.g. if all is big and bold, nothing stands out. 

#### P5: priciple of perceptual organization
	* people automatically group elements into units, which they can attend to and remember

perceptual rules: proximity, similarity, continuity (smooth curve), coherence (motion), form simple shapes*Perceptual organization: Pragnanz求简, similarity, proximity, good continuation, common fate (move together), common region, uniform connectedness, synchrony, meaningfulness↑notes from my perception courseGoal 3: Promote understanding and memory 

#### P6: principle of compaticility
	* 
a messege is easiest to understand if its form is compatible with its meaning. 
	* 
e.g.: illustrate number/time from left to right
	* 
"more is more": a larger area/ longer bar conveys "more" by instinct  (explain or change when "more is less")


#### P7: principle of informative changes
	* 
every visible/ auditory change should convey information
	* 
every change in meaning should be conveyed by a change in appearance 



#### P8: principle of capacity limitations: no too much information at the same time
	* rule of four: the audience cannot hold in mind more than four groups of information at once 
	* break down the points/ define perceptual groups with cues
	* reduce audience's need to search for/ mentally transform information 


e.g.: present tables when you are mentalizing a table while speaking
